version: '3'
services:
  abc2023:
    container_name: abc2023
    build:
      dockerfile: Dockerfile
      args:
        - IMAGE="python:3.9-buster"
    ports:
      - "8888:8888"
    volumes:
        - ./:/workspaces/
    ## If you have a GPU, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0']
    #           capabilities: [gpu]
